inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.2

Style/AndOr:
  EnforcedStyle: conditionals

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation
